name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.763
      - run: clojure -Mdev:test

  test-dei:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.763
      - run: cd projects/dei && clojure -Mdev:test

  test-deddie:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: DeLaGuardo/setup-clojure@master
        with:
          cli: 1.10.1.763
      - run: cd projects/deddie && clojure -Mdev:test
